server:
  host: localhost
  port: 8080

database:
  driver: mysql
  host: localhost
  port: 3306
  name: goframe
  user: root
  password: 

auth:
  secret: your-secret-key-here
  duration: 24h

rateLimit:
  requests: 100
  period: 1m

app:
  name: goframe
  version: 1.0.0
